### ISSUE TITLE
controller 报错

### ISSUE THREAD

**Issue by LeezQ** [xieyezi/flutter-getx-template#4]
![image](https://user-images.githubusercontent.com/972813/127294135-09f32a60-2385-4399-812f-92b594f2a246.png)

为什么这么写，controller 找不到。

明明已经绑定了。
![image](https://user-images.githubusercontent.com/972813/127294213-48a7e35d-3d23-420b-aff5-08e9d7619b66.png)

**Comment by xieyezi** [comment]
@LeezQ 
不好意思，过了这么久才看见issuse，不知道你是否已经解决
我猜测可能的原因是因为，在main.dart里面，初始化getx的时候，有个`initialBinding`属性，你得把`LoginBindings`加入到`initialBinding `里面，如果是用的此模板，`initialBinding`已经指定为`IndexBinding`，所以你只需要在`IndexBinding`里面加入`LoginController`即可。
希望还能帮助到你！

**Comment by hhstore** [comment]
- Controller 找不到, 通常是你没有调用到 get.put<Controller>() 这类方法. 
- 如果你是使用的是 Get.toNamed() 这种命名路由, 要注意检查 initialBinding() 里的 Get.put() 是不是加了你这个 view 对应的. 
- 如果没加, 要加一下. 
- 如果是 Get.to(LoginPage()) 这种方式调用, 你需要在 app 启动, 譬如首页的 HomeBinding() 里, 手动添加 Get.put<your-Controller>() 这种. 保证你的 Controller, 被初始化了. 
- extends Getview<> 这种写法, 本身没有初始化 Controller 的. 需要你提前先初始化. 
- 你看一下 GetView() 的源码, 就明白了.

**Comment by hhstore** [comment]
- loginBinding 添加了. 只是保证你使用 Get.toNamed() 方式, 调用页面, 好使. 因为 loginBinding() 是在 全局 routes 表里, 使用了. 
- 但是, 当你使用 Get.to(page()) 方式, 跳转页面. 并不会走到 loginBinding() 的代码. 
- 这种情况, 你需要找到一个 app 最早打开的一个页面, 譬如 HomePage 的 HomeBinding(), 然后你手动在这里, 添加一条 Get.put<Controller>. 
- 这样, 保证你的 Controller 是被初始化的. 就不会有问题了.

**Comment by hhstore** [comment]
- 本质是 GetView<Controller> 这个写法, 只是用 Get.find<>, 而不是 Get.put<>, 所以少了容错. 
- 多说一句. Get.put<> 内部调用了 Get.find<>, 所以 Get.put<> 的返回值, 等于 Get.find<>. 这个特性, 可以利用.

**Comment by huanlirui** [comment]
> @LeezQ 不好意思，过了这么久才看见issuse，不知道你是否已经解决 我猜测可能的原因是因为，在main.dart里面，初始化getx的时候，有个`initialBinding`属性，你得把`LoginBindings`加入到`initialBinding `里面，如果是用的此模板，`initialBinding`已经指定为`IndexBinding`，所以你只需要在`IndexBinding`里面加入`LoginController`即可。 希望还能帮助到你！

怎么在 `IndexBinding`里面加入`LoginController` ？？能贴下代码吗。。

**Comment by huanlirui** [comment]
class IndexBinding extends Bindings {
  @override
  void dependencies() {
    Get.lazyPut<IndexController>(() => IndexController());
    Get.lazyPut<HomeController>(() => HomeController());
  }
}

是这样吗？也就是说需要在IndexBinding中所有页面中所有的controller都lazyPut一下？

**Comment by hhstore** [comment]
> class IndexBinding extends Bindings { @OverRide void dependencies() { Get.lazyPut(() => IndexController()); Get.lazyPut(() => HomeController()); } }
> 
> 是这样吗？也就是说需要在IndexBinding中所有页面中所有的controller都lazyPut一下？

参考我上面的回复.


- 确保在 app 首次打开页面的 bindings(不一定是IndexBinding) 里, 注册你希望预先加载的 Controller 数据层.
- Get.put() 实际注册到一个全局 map 里. 
- 不需要所有的 Controller 都放首个 binding 里. 按需添加.

**Comment by huanlirui** [comment]
> > class IndexBinding extends Bindings { @OverRide void dependencies() { Get.lazyPut(() => IndexController()); Get.lazyPut(() => HomeController()); } }
> > 是这样吗？也就是说需要在IndexBinding中所有页面中所有的controller都lazyPut一下？
> 
> 参考我上面的回复.
> 
> * 确保在 app 首次打开页面的 bindings(不一定是IndexBinding) 里, 注册你希望预先加载的 Controller 数据层.
> * Get.put() 实际注册到一个全局 map 里.
> * 不需要所有的 Controller 都放首个 binding 里. 按需添加.

理解了。首次打开的页面，需要预先加载的才放到indexbidings里面。而其他页面，只要通过get.toname去访问，都已经在appRouter注册过biding了，所以不需要再添加了。

**Comment by hhstore** [comment]
对的
